server:
  port: 80


# 服务别名 --- 注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      connect-string: 192.168.109.131:2181  # 如果zookeeper 是集群，则逗号分隔，如：192.168.109.131:2181 ,192.168.109.132:2181