server:
  port: 80

spring:
  application:
    name: cloud-provider-hystrix-order

eureka:
  client:
    register-with-eureka: true # 将自己注册到eureka
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

# 配置openfeign的日志
logging:
  level:
    com.atguigu.springcloud.config.FeignConfig: debug

# 此时使用基于openfeign 的服务降级，需要开启（和直接使用hystrix在启动类上不同）
feign:
  hystrix:
    enabled: true
